### ISSUE TITLE
Unknown compiler warning ignored when compiling with gcc

### ISSUE THREAD

**Issue by TheWaveWarden** [sonible/VCTR#103]
When compiling my project under Ubuntu with gcc, I get a lot of warnings regarding an unknown compiler warning `return-stack-address`. And yes, this warning doesn't seem to exist for gcc: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html :slightly_smiling_face: 
![image](https://github.com/sonible/VCTR/assets/28705282/376cc0c9-1755-4a94-92ea-6b6ff8e24235)

**Comment by JanosGit** [comment]
Does it compile the line without warnings if you simply comment it out?

**Comment by TheWaveWarden** [comment]
@JanosGit yes that's my workaround currently and no warnings are generated.

I'm happy to put together a little PR with this change if wanted. I think the `VCTR_START_IGNORE_WARNING_CLANG_GCC` macro would need to be split into two separate ones and only activated for clang in this case.

**Comment by JanosGit** [comment]
I see. I think we should add a macro that only suppresses this warning for clang

**Comment by JanosGit** [comment]
A fix is on the way along with the current PR which needed some extension of the warning suppression macros anyway

**Comment by TheWaveWarden** [comment]
Alright! Thank you very much! 🙂
